### ISSUE TITLE
CORS policy not allowed

### ISSUE THREAD

**Issue by hanapelikanova** [robofit/arcor2#122]
It is not possible to connect to arcor execution service via kinali web ui, it is probably due to unallowed CORS policy in arcor execution service. 

![Capture](https://user-images.githubusercontent.com/61684291/82549144-c3a6b380-9b5c-11ea-8650-1dffa2aa9f70.PNG)

**Comment by ZdenekM** [comment]
@hanapelikanova Should be fixed by https://github.com/robofit/arcor2/pull/124. Is this urgent? Should be make a new release with this fix?

**Comment by martincervinka** [comment]
Yes, it has the highest priority, we would like to test the TIO production setup.

**Comment by ZdenekM** [comment]
Ok, we will make the release soon.

**Comment by Kapim** [comment]
Released as 0.4.3
