### ISSUE TITLE
Use platform specific function

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2#133]
Is it ok? Should have be only on Unix OS?
https://docs.python.org/3.8/library/select.html#select.select

On Windows:
OSError: [WinError 10038] An operation was attempted on something that is not a socket.

**Comment by ZdenekM** [comment]
ARCOR2 is not tested at all on Windows. So far, we suggest to use it only on Linux.

**Comment by ZdenekM** [comment]
Fixed by https://github.com/robofit/arcor2/commit/533f8aae9f2b27f84229b9872762c6ea95ae628b. 
Btw, next time please attach the traceback (file with traceback should appear within the package folder). Many thanks in advance :-)
