### ISSUE TITLE
MeshParameters missing property uri

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2#323]
In class model MeshParameters should be required parameter uri (https://github.com/robofit/arcor2/blob/8498b68501c9fcf387f44b2b66e7f4149e461e19/src/python/arcor2/clients/scene_service.py#L22)

**Comment by ZdenekM** [comment]
`uri` is defined in the `Mesh` model: https://github.com/robofit/arcor2/blob/8498b68501c9fcf387f44b2b66e7f4149e461e19/src/python/arcor2/data/object_type.py#L88

So adding a mesh with some additional parameters would look like this:

```python
scene_service.upsert_collision(Mesh("http://mesh_uri/mesh.stl"), Pose(), MeshParameters(1.1, 1.1, 1.1))
```

**Comment by NelaMm** [comment]
Ok, thanks.
