### ISSUE TITLE
Divide KinaliRobot into Simatic and Aubo

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2#353]
This will improve work with AREditor - right now, it is not possible to check that some features are not supported (e.g. moving to a pose for Simatic robot). Moreover, we will be able to add URDF model for each robot (at least for Aubo).

**Comment by ZdenekM** [comment]
@martincervinka Is it ok to add URDF of the Aubo robot to this repo?

**Comment by martincervinka** [comment]
> @martincervinka Is it ok to add URDF of the Aubo robot to this repo?

Yes, it's OK.
