### ISSUE TITLE
Misleading message when deleting nonexistent execution package

### ISSUE THREAD

**Issue by jirzajic** [robofit/arcor2#371]
**Found in version**
- via swagger ARCOR2 Execution Service Proxy (0.8.2)  0.4.0 OAS3

**Perform the following steps reproduce the bug**
- execute [DELETE] /packages/{packageId} with packageId which does not exist

**Observed results**
- 501 Error: NOT_IMPLEMENTED "Package does not contain main script."

**Expected results**
- Not sure about error code, maybe 404, but message like "Package with given id does not exist" would be more helpful for client

**Comment by ZdenekM** [comment]
Definitely... The issue was fixed in https://github.com/robofit/arcor2/pull/373.
