### ISSUE TITLE
Call non-existing method in class aubo in arcor2_kinali

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2#400]
In Robot API 0.9.0 method moveJointsCollideLessRelative not exist:
https://github.com/robofit/arcor2/blob/ed3df654f252529267924595e5097caef1be70cd/src/python/arcor2_kinali/object_types/aubo.py#L141

**Comment by ZdenekM** [comment]
Sorry for the inconvenience, fixed in https://github.com/robofit/arcor2/pull/403.
