### ISSUE TITLE
"'NoneType' object is not callable" thrown when cleaning up the resources

### ISSUE THREAD

**Issue by Croolman** [robofit/arcor2#544]
When `Resources` object is destroyed a type exception with mentioned message is thrown. The issue was localized to be in `resources.py` on line 121-122. After commenting out those lines, everything works as intended.

https://github.com/robofit/arcor2/blob/4925dd4206e0e91971e71e077cdc8eebe644c58e/src/python/arcor2/resources.py#L121-L122

**Comment by ZdenekM** [comment]
Fixed in https://github.com/robofit/arcor2/pull/545/commits/fa0b443fd6cf5d1a6a5f5146a1d50fed21563d04, will be part of the next release. Thanks for reporting!
