### ISSUE TITLE
Improve work with execution packages

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2#85]
- [x] Read scene/project from running execution package and forward it to Editor.
- [x] Rename RunProject etc. to RunPackage.
- [x] Add "project_id" to ListPackagesResponse/PackageSummary.
- [x] ~~Enable work on project while execution package runs (only if the scene is same?), just disable action execution.~~
- [x] event to get collision models built into package (collision models of ObjectTypes from Project service cannot be used as they might be different, non-existent, etc.).
- [x] Decide if package directory name should be its id or name. Add package.json (with id, name, build timestamp?).

**Comment by Kapim** [comment]
- [ ] Add name to ListPackagesResponse/PackageSummary
- [ ] Add name to BuildPackage

**Comment by ZdenekM** [comment]
Work on project while package runs could be enabled in the future - it has to be decided what should and what should not be possible to do.

**Comment by ZdenekM** [comment]
@Kapim Maybe, we might merge SceneCollisions into PackageInfo? Original idea was to have it separately in order to allow dynamic updates of collision models but it is not needed now and maybe it complicates things a bit. What do you think? Anyway, collision models of the objects should not change during script runtime.

**Comment by Kapim** [comment]
I am definitely all for it. I have not implemented this yet and the merge will simplify it for me.

**Comment by ZdenekM** [comment]
Ok. Done in https://github.com/robofit/arcor2/commit/4e6c6753117d0b855633ec9588bc90b04e7b3fd2.
