### ISSUE TITLE
Locking the same thing

### ISSUE THREAD

**Issue by JosefKnize** [robofit/arcor2#851]
Sometimes client app end's up in faulty state where object is unlocked even thou it is locked on server. In this scenario server refuses any locking request for that object.

Quick fix would be for server to simply accept locking request if the requester owns the lock for that object.

**Comment by ZdenekM** [comment]
Thanks, probably a good idea. One just has to keep in mind that it is a workaround - in the first place, a client application should handle locking properly - it should know what is locked and by whom. So we can make it, but the server will print out a warning when this happens.
